sudo: required
services:
  - docker
before_install:
  - gem install bundler --pre
  - docker build -t sachin/docker-react -f Dockerfile.dev .
script:
  - docker run sachin/docker-react npm run test -- --coverage

